version: "3"
services:
  importer-my:
    build:
      context: './crawler'
      dockerfile: './Dockerfile-importer'
    networks: ''
    env_file:
      - db-variables.env
    environment:
      IMPORT_FILE: '/var/lib/test-lists/lists/my.env'
    volumes:
      - ./test-lists:/var/lib/test-lists
    restart: no
  crawler-my:
    build:
      context: './crawler'
      dockerfile: './Dockerfile-crawler'
    networks: ''
    env_file:
      - db-variables.env
    environment:
      COUNTRY_CODE: 'MY'
    restart: always